/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : system-volume
 #	author : miyako
 #	2015/07/08
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#if VERSIONMAC
//https://github.com/InerziaSoft/ISSoundAdditions/blob/master/ISSoundAdditions.m
AudioDeviceID obtainDefaultOutputDevice()
{
    AudioDeviceID theAnswer = kAudioObjectUnknown;
    UInt32 theSize = sizeof(AudioDeviceID);
    AudioObjectPropertyAddress theAddress;
	
	theAddress.mSelector = kAudioHardwarePropertyDefaultOutputDevice;
	theAddress.mScope = kAudioObjectPropertyScopeGlobal;
	theAddress.mElement = kAudioObjectPropertyElementMaster;
	
	//first be sure that a default device exists
	if(!AudioObjectHasProperty(kAudioObjectSystemObject, &theAddress)){
		NSLog(@"Unable to get default audio device");
		return theAnswer;
	}
	//get the property 'default output device'
    OSStatus theError = AudioObjectGetPropertyData(kAudioObjectSystemObject, &theAddress, 0, NULL, &theSize, &theAnswer);
    if(theError != noErr){
		NSLog(@"Unable to get output audio device");
		return theAnswer;
	}
    return theAnswer;
}
#else
const CLSID CLSID_MMDeviceEnumerator = __uuidof(MMDeviceEnumerator);
const IID IID_IMMDeviceEnumerator = __uuidof(IMMDeviceEnumerator);
const IID iidAEV = __uuidof(IAudioEndpointVolume);

// Acquires the default render endpoint's IAudioEndpointVolume and releases it
// (and, earlier, the enumerator and device) on every path. The original code
// never released IAudioEndpointVolume, leaking one reference per call.
struct EndpointVolume
{
    IAudioEndpointVolume *ep;

    EndpointVolume() : ep(NULL)
    {
        IMMDeviceEnumerator *pDevEnum = NULL;
        IMMDevice *pDev = NULL;

        if(SUCCEEDED(CoCreateInstance(CLSID_MMDeviceEnumerator, NULL, CLSCTX_ALL, IID_IMMDeviceEnumerator, (void**)&pDevEnum))){
            if(SUCCEEDED(pDevEnum->GetDefaultAudioEndpoint(eRender, eConsole, &pDev))){
                if(FAILED(pDev->Activate(iidAEV, CLSCTX_ALL, NULL, (void**)&ep))){
                    ep = NULL;
                }
                pDev->Release();
            }
            pDevEnum->Release();
        }
    }

    ~EndpointVolume()
    {
        if(ep){
            ep->Release();
        }
    }

private:
    EndpointVolume(const EndpointVolume&);
    EndpointVolume& operator=(const EndpointVolume&);
};
#endif

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- System Volume

		case 1 :
			AUDIO_SET_VOLUME(pResult, pParams);
			break;

		case 2 :
			AUDIO_Get_volume(pResult, pParams);
			break;

		case 3 :
			AUDIO_SET_MUTE(pResult, pParams);
			break;

		case 4 :
			AUDIO_Get_mute(pResult, pParams);
			break;

	}
}

// --------------------------------- System Volume --------------------------------

void AUDIO_SET_VOLUME(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_REAL Param1;
    
	Param1.fromParamAtIndex(pParams, 1);

#if VERSIONMAC
	AudioObjectPropertyAddress	theAddress;
	AudioDeviceID				defaultDevID;
	OSStatus					theError = noErr;
	Boolean						canSetVol = YES;
	double						dValue = Param1.getDoubleValue();

	// ignore NaN; clamp in double BEFORE narrowing to float
	if(dValue != dValue) return;
	dValue = dValue > 1.0 ? 1.0 : (dValue < 0.0 ? 0.0 : dValue);
	float newValue = (float)dValue;

    if((newValue < THRESHOLD)){
        AUDIO_SET_MUTE(0);
    }else{
    
        defaultDevID = obtainDefaultOutputDevice();
        
        if(defaultDevID != kAudioObjectUnknown){
        
            theAddress.mElement = kAudioObjectPropertyElementMaster;
            theAddress.mScope = kAudioDevicePropertyScopeOutput;
            theAddress.mSelector = kAudioHardwareServiceDeviceProperty_VirtualMasterVolume;
            
            if(AudioObjectHasProperty(defaultDevID, &theAddress)){
            
                theError = AudioObjectIsPropertySettable(defaultDevID, &theAddress, &canSetVol);
                
                if(theError == noErr && canSetVol){
                
                    AudioObjectSetPropertyData(defaultDevID, &theAddress, 0, NULL, sizeof(newValue), &newValue);

                }
            }
        }
    }
#else

    double dVolume = Param1.getDoubleValue();

    // ignore NaN; clamp in double BEFORE narrowing to float
    if(dVolume != dVolume) return;
    dVolume = dVolume > 1.0 ? 1.0 : (dVolume < 0.0 ? 0.0 : dVolume);
    float fVolume = (float)dVolume;
    
    if((fVolume < THRESHOLD)){
        AUDIO_SET_MUTE(FALSE);
    }else{ 
        
        EndpointVolume v;
        if(v.ep){
            v.ep->SetMasterVolumeLevelScalar(fVolume, NULL);
        }
        
    }
#endif    
}

void AUDIO_Get_volume(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_REAL returnValue;

#if VERSIONMAC	
    AudioDeviceID				defaultDevID = kAudioObjectUnknown;
	UInt32						theSize = sizeof(Float32);
	OSStatus					theError;
	Float32						theVolume = 0;
	AudioObjectPropertyAddress	theAddress;
    
    defaultDevID = obtainDefaultOutputDevice();
    
	if(defaultDevID != kAudioObjectUnknown){

        theAddress.mElement = kAudioObjectPropertyElementMaster;    
        theAddress.mScope = kAudioDevicePropertyScopeOutput;
        theAddress.mSelector = kAudioHardwareServiceDeviceProperty_VirtualMasterVolume;
        
        if(AudioObjectHasProperty(defaultDevID, &theAddress)){
		
            theError = AudioObjectGetPropertyData(defaultDevID, &theAddress, 0, NULL, &theSize, &theVolume);
            
            if(theError == noErr){

                returnValue.setDoubleValue(theVolume > 1.0 ? 1.0 : (theVolume < 0.0 ? 0.0 : theVolume));

            }
        }
    }
#else
    float fVolume = 0;
    EndpointVolume v;
    
    if(v.ep && SUCCEEDED(v.ep->GetMasterVolumeLevelScalar(&fVolume))){
        returnValue.setDoubleValue(fVolume);
    }
#endif
    
	returnValue.setReturn(pResult);
}

#if VERSIONMAC
void AUDIO_SET_MUTE(UInt32 muted){

    AudioDeviceID				defaultDevID = kAudioObjectUnknown;
	AudioObjectPropertyAddress	theAddress;
	Boolean						canMute = YES;
	OSStatus					theError = noErr;
        
    defaultDevID = obtainDefaultOutputDevice();
    
	if(defaultDevID != kAudioObjectUnknown){
    
        theAddress.mElement = kAudioObjectPropertyElementMaster;
        theAddress.mScope = kAudioDevicePropertyScopeOutput;
        theAddress.mSelector = kAudioDevicePropertyMute;    
        
        if(AudioObjectHasProperty(defaultDevID, &theAddress)){
        
            theError = AudioObjectIsPropertySettable(defaultDevID, &theAddress, &canMute);
            
            if(theError == noErr && canMute){
            
                theError = AudioObjectSetPropertyData(defaultDevID, &theAddress, 0, NULL, sizeof(muted), &muted);

            }
        }
	}
}
#endif

#if VERSIONWIN
void AUDIO_SET_MUTE(BOOL bMute)
{
    EndpointVolume v;
    
    if(v.ep){
        v.ep->SetMute(bMute, NULL);
    }
}
#endif

void AUDIO_SET_MUTE(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT Param1;

	Param1.fromParamAtIndex(pParams, 1);

#if VERSIONMAC
    AUDIO_SET_MUTE(Param1.getIntValue() ? 1 : 0);
#else
    AUDIO_SET_MUTE(Param1.getIntValue() ? TRUE : FALSE);
#endif    
}

void AUDIO_Get_mute(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT returnValue;

#if VERSIONMAC
    AudioDeviceID				defaultDevID = kAudioObjectUnknown;
	UInt32						theSize = sizeof(UInt32);
	OSStatus					theError;
	UInt32						muted = 0;
	AudioObjectPropertyAddress	theAddress;
    
    defaultDevID = obtainDefaultOutputDevice();
    
	if(defaultDevID != kAudioObjectUnknown){

        theAddress.mElement = kAudioObjectPropertyElementMaster;    
        theAddress.mScope = kAudioDevicePropertyScopeOutput;
        theAddress.mSelector = kAudioDevicePropertyMute;
        
        if(AudioObjectHasProperty(defaultDevID, &theAddress)){
		
            theError = AudioObjectGetPropertyData(defaultDevID, &theAddress, 0, NULL, &theSize, &muted);
            
            if(theError == noErr){

                returnValue.setIntValue(muted ? 1 : 0);

            }
        }
    }
#else
    BOOL bMute = FALSE;
    EndpointVolume v;
    
    if(v.ep && SUCCEEDED(v.ep->GetMute(&bMute))){
        returnValue.setIntValue(bMute ? 1 : 0);
    }
#endif

	returnValue.setReturn(pResult);
}